version: "3"

services:
  oracle-db:
    image: wnameless/oracle-xe-11g-r2:latest
    container_name: oracledb
    ports:
      - 49161:1521
    volumes:
      - oracle_volume:/u01/app/oracle

volumes:
  oracle_volume:
