version: "3"

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgresql_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=rohanmohapatra
      - POSTGRES_PASSWORD=rohanmohapatra

volumes:
  postgresql_volume:
