version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rohanmohapatra
      - MYSQL_PASSWORD=rohanmohapatra
      - MYSQL_DATABASE=test

volumes:
  mysql_volume:
