version: "3"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - cass_volume:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra

volumes:
  cass_volume:
